# Generated by Django 5.0.6 on 2024-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(choices=[('DUVIDAS', 'Dúvidas'), ('ORCAMENTOS', 'Orçamentos'), ('PROJETOS', 'Projetos'), ('FEEDBACK', 'Feedback'), ('SUGESTAO', 'Sugestão'), ('BUG', 'Bug'), ('OUTROS', 'Outros')], default='', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
