# Generated by Django 5.0.6 on 2024-08-10 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FRONT_END', 'Front-end'), ('BACK_END', 'Back-end'), ('DESIGN', 'Design'), ('BUSINESS', 'Negócios'), ('TUTORIALS', 'Tutoriais'), ('TECNOLOGIA', 'Tecnologia'), ('PHOTOGRAPHY', 'Fotografia'), ('ARTE', 'Arte'), ('GAMING', 'Gaming'), ('GEEK', 'Geek'), ('CINEMA_TV', 'Cinema e TV'), ('TRAVEL', 'Viagem'), ('BOOKS', 'Livros'), ('RECEITAS', 'Receitas'), ('FASHION', 'Moda'), ('LIFESTYLE', 'Lifestyle'), ('VINME', 'Vinme')], default='FRONT_END', max_length=50),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
