# Generated by Django 5.0.6 on 2024-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_media_section_media_content_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsection',
            options={'verbose_name_plural': 'Content Sections'},
        ),
        migrations.AddField(
            model_name='contentsection',
            name='images_or_videos',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
