# Generated by Django 5.0.6 on 2024-08-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentsection',
            old_name='images_or_videos',
            new_name='images_or_videos1',
        ),
        migrations.AddField(
            model_name='contentsection',
            name='images_or_videos2',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='images_or_videos3',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='images_or_videos4',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='images_or_videos5',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
