# Generated by Django 5.0.6 on 2024-08-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_images_or_videos_contentsection_images_or_videos1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
